const SUPABASE_URL="https://wfxaacrxolofifflwsak.supabase.co";
const SUPABASE_KEY="sb_publishable_2mx_ZxJMnKa9hZHOYLHqQQ_aIDNXpwK";
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const PROJECTS_FALLBACK=[["EVORA","Luxury fragrance / Brand world","01","SIGNATURE"],["THE CLOSET","Fashion / Editorial identity","02","THE CLOSET"],["ASAS","Real estate / Brand system","03","ASAS"],["MILESTONE","Engineering / Corporate identity","04","MILESTONE"]];
const SERVICES_FALLBACK=[["01","Brand Identity & Strategy","Positioning, naming, visual systems, art direction and guidelines."],["02","Digital Experiences","Websites, UI/UX and digital systems that feel premium and effortless."],["03","Campaigns & Content","Launch concepts, motion and creative campaigns designed to be noticed."],["04","Growth Creative","Creative direction for paid media, conversion journeys and measurable growth."]];
const PRICES={UAE:["AED",[3000,6000,10000]],KSA:["SAR",[6500,13000,22000]],KWT:["KWD",[250,500,850]],EGY:["EGP",[45000,85000,140000]]};
const OPTIONS=[["posts","Social posts",500],["stories","Stories",250],["reels","Reels",700],["video","Product / Promo Video",1500],["motion","Motion Graphics",1200],["landing","Landing Page",2500],["website","Website",6000],["seo","SEO",2000],["strategy","Strategy & Support",1500],["ads","Ads Management",1800]];
let market="UAE",total=3000,projects=PROJECTS_FALLBACK,services=SERVICES_FALLBACK;

const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function renderProjects(rows){projects=rows?.length?rows.map((p,i)=>[p.name||p.client_name||"PROJECT",p.short_description||p.category||"Creative project",String(i+1).padStart(2,"0"),p.cover_url||p.category||"ZERO ONE",p.slug||""]):PROJECTS_FALLBACK;$("#projects").innerHTML=projects.map(p=>'<article class="project" data-slug="${esc(p[4])}"><div class="project-visual">'+(p[3].startsWith?.("http")?'<img src="'+esc(p[3])+'" alt="'+esc(p[0])+'">':'<div class="project-art">'+esc(p[3])+"</div>")+'</div><div class="project-meta"><div><h3>'+esc(p[0])+'</h3><p>'+esc(p[1])+" · 2026</p></div><span>↗</span></div></article>").join("");}
function renderServices(rows){services=rows?.length?rows.map((s,i)=>[String(i+1).padStart(2,"0"),s.name,s.short_description||s.description||""]):SERVICES_FALLBACK;$("#services-list").innerHTML=services.map(s=>'<article class="service"><span>'+s[0]+'</span><div><h3>'+esc(s[1])+'</h3><p>'+esc(s[2])+'</p></div><b>↗</b></article>').join("");}
function renderPricing(){const [cur,ps]=PRICES[market];$("#plans").innerHTML=ps.map((p,i)=>'<article class="plan '+(i===1?"popular":"")+'"><small>0'+(i+1)+" / "+["STARTER","GROWTH","PREMIUM"][i]+'</small><h3>'+["Starter","Growth","Premium"][i]+'</h3><div class="price">'+cur+" "+p.toLocaleString()+'<small> / MONTH</small></div><ul><li>Creative direction</li><li>Monthly content system</li><li>Strategy & reporting</li><li>Priority support</li></ul><button data-contact>Start a conversation ↗</button></article>').join("");total=ps[0];$("#total").textContent=cur+" "+total.toLocaleString();}
function renderBuilder(){$("#builder-options").innerHTML=OPTIONS.map(o=>'<label class="option"><span>'+o[1]+'</span><input type="checkbox" data-price="'+o[2]+'" data-name="'+esc(o[1])+'"></label>').join("");$("#builder-options").onchange=calc;}
function calc(){const [cur,min]=PRICES[market];let sum=min[0],chosen=[];document.querySelectorAll("#builder-options input:checked").forEach(x=>{sum+=+x.dataset.price;chosen.push(x.dataset.name)});total=sum;$("#total").textContent=cur+" "+sum.toLocaleString();$("#wa").dataset.message="Market: "+market+"\nEstimated monthly investment: "+cur+" "+sum.toLocaleString()+"\nSelected: "+chosen.join(", ");}
async function loadCMS(){if(!db)return;try{const [p,s,pr,content,logos]=await Promise.all([db.from("projects").select("slug,name,client_name,category,short_description,cover_url,description,gallery,services,year,seo_title,seo_description").eq("status","published").order("sort_order"),db.from("services").select("name,short_description,description").eq("status","published").order("sort_order"),db.from("pricing_plans").select("*").eq("status","published").eq("market",market).order("sort_order"),db.from("site_content").select("*").eq("status","published"),db.from("client_logos").select("*").eq("status","published").order("sort_order")]);if(!p.error)renderProjects(p.data);if(!s.error)renderServices(s.data);if(!content.error&&content.data?.length)applySiteContent(content.data);if(!logos.error&&logos.data?.length)renderClientLogos(logos.data);if(!pr.error&&pr.data?.length){const grouped=pr.data.slice(0,3);const cur=grouped[0].currency;const ps=grouped.map(x=>Number(x.amount));PRICES[market]=[cur,ps];renderPricing();calc();}}catch(e){console.warn("CMS fallback",e)}}
async function submitLead(e){e.preventDefault();const form=e.target,d=Object.fromEntries(new FormData(form));const payload={name:d.name,company:d.company,email:d.email,phone:d.phone,whatsapp:d.phone,message:d.message,service_interest:d.service,source:"website",market:market,status:"new"};if(db){const {error}=await db.from("leads").insert(payload);if(error){console.error(error);$("#form-status").textContent="We couldn't send the enquiry. Please use WhatsApp.";return;}}$("#form-status").textContent="Enquiry received. We’ll get back to you shortly.";form.reset();}
async function adminSignIn(){const email=$("#admin-email").value.trim(),pass=$("#admin-pass").value;if(!db||!email||!pass){$("#admin-msg").textContent="Enter valid credentials.";return}const {error}=await db.auth.signInWithPassword({email,password:pass});if(error){$("#admin-msg").textContent=error.message;return}await openDashboard();}
async function openDashboard(){const {data:{user}}=await db.auth.getUser();if(!user){$("#admin-msg").textContent="Sign in required.";return}const role=user.app_metadata?.role;if(role!=="admin"){$("#admin-msg").textContent="This account is not an admin.";await db.auth.signOut();return}$("#admin-login").hidden=true;$("#admin-dash").hidden=false;const tables=["leads","projects","services","pricing_plans"];const counts=await Promise.all(tables.map(t=>db.from(t).select("id",{count:"exact",head:true})));["a-leads","a-projects","a-services","a-plans"].forEach((id,i)=>{$("#"+id).firstChild.textContent=counts[i].count||0});await adminData("leads");}
document.querySelectorAll(".market-tabs button").forEach(b=>b.onclick=async()=>{market=b.dataset.market;document.querySelectorAll(".market-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPricing();calc();await loadCMS();});
$("#wa").onclick=()=>{const msg=$("#wa").dataset.message||"I want to build a custom ZERO ONE package.";location.href="https://wa.me/201556764804?text="+encodeURIComponent(msg)};
$("#lead-form").onsubmit=submitLead;
$("#admin-link").onclick=async()=>{ $("#admin").classList.add("open"); if(db){const {data:{session}}=await db.auth.getSession();if(session)await openDashboard();}};
$("#admin-signin").onclick=adminSignIn;
$("#close-admin").onclick=async()=>{$("#admin").classList.remove("open");if(db)await db.auth.signOut();$("#admin-login").hidden=false;$("#admin-dash").hidden=true;};
document.addEventListener("click",e=>{if(e.target.matches("[data-contact]"))location.hash="contact";});
window.addEventListener("scroll",()=>{$(".scroll-progress span").style.width=(scrollY/(document.body.scrollHeight-innerHeight)*100)+"%"});
renderProjects();renderServices();renderPricing();renderBuilder();loadCMS();

(function(){const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const setup=()=>{document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",()=>{const el=document.querySelector(a.getAttribute("href"));if(el)el.scrollIntoView({behavior:reduced?"auto":"smooth"})}));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".project,.service,.plan,.process-grid article,.about-grid,.builder").forEach(e=>{e.classList.add("reveal-ready");io.observe(e)});const hero=document.querySelector(".hero-art"),island=document.querySelector(".island-stage");if(hero&&!reduced&&window.matchMedia("(pointer:fine)").matches)hero.addEventListener("pointermove",e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;island.style.transform="translate("+x*18+"px,"+y*14+"px)"});hero?.addEventListener("pointerleave",()=>island.style.transform="");document.querySelector(".menu")?.addEventListener("click",()=>document.querySelector(".nav-wrap").classList.toggle("mobile-open"));};setup();})();
async function adminData(tab){
 if(!db)return;
 const target=$("#admin-content");
 target.innerHTML='<p>Loading...</p>';
 if(tab==="leads"){const {data,error}=await db.from("leads").select("id,name,email,company,service_interest,market,status,created_at").order("created_at",{ascending:false}).limit(100);if(error){target.innerHTML="<p>"+esc(error.message)+"</p>";return}target.innerHTML='<div class="cms-head"><h3>Leads</h3><span>'+((data||[]).length)+' records</span></div><div class="cms-list">'+(data||[]).map(l=>'<div class="cms-row"><div><b>'+esc(l.name)+'</b><small>'+esc(l.company||"")+' · '+esc(l.email)+'</small></div><span>'+esc(l.service_interest||"—")+'</span><select data-lead="'+l.id+'"><option '+(l.status==="new"?"selected":"")+' value="new">New</option><option '+(l.status==="contacted"?"selected":"")+' value="contacted">Contacted</option><option '+(l.status==="qualified"?"selected":"")+' value="qualified">Qualified</option><option '+(l.status==="proposal"?"selected":"")+' value="proposal">Proposal</option><option '+(l.status==="won"?"selected":"")+' value="won">Won</option><option '+(l.status==="lost"?"selected":"")+' value="lost">Lost</option></select></div>').join("")+"</div>";target.querySelectorAll("[data-lead]").forEach(s=>s.onchange=async()=>{await db.from("leads").update({status:s.value}).eq("id",s.dataset.lead)})}
 if(tab==="projects"){const {data,error}=await db.from("projects").select("id,name,category,status,featured,sort_order").order("sort_order");if(error){target.innerHTML="<p>"+esc(error.message)+"</p>";return}target.innerHTML='<div class="cms-head"><h3>Projects</h3><button id="new-project">+ Add project</button></div><div class="cms-list">'+(data||[]).map(p=>'<div class="cms-row"><div><b>'+esc(p.name)+'</b><small>'+esc(p.category||"")+'</small></div><span>'+esc(p.status)+'</span><button data-project="'+p.id+'">Toggle publish</button></div>').join("")+"</div>";target.querySelector("#new-project").onclick=()=>cmsForm("project");target.querySelectorAll("[data-project]").forEach(b=>b.onclick=()=>cmsForm("project",data.find(x=>x.id===b.dataset.project)))}
 if(tab==="services"){const {data,error}=await db.from("services").select("id,name,status,featured,sort_order").order("sort_order");if(error){target.innerHTML="<p>"+esc(error.message)+"</p>";return}target.innerHTML='<div class="cms-head"><h3>Services</h3><button id="new-service">+ Add service</button></div><div class="cms-list">'+(data||[]).map(s=>'<div class="cms-row"><div><b>'+esc(s.name)+'</b></div><span>'+esc(s.status)+'</span><button data-service="'+s.id+'">Toggle publish</button></div>').join("")+"</div>";target.querySelector("#new-service").onclick=()=>cmsForm("service");target.querySelectorAll("[data-service]").forEach(b=>b.onclick=()=>cmsForm("service",data.find(x=>x.id===b.dataset.service)))}
 if(tab==="content"){const {data,error}=await db.from("site_content").select("*").order("content_key");if(error){target.innerHTML="<p>"+esc(error.message)+"</p>";return}target.innerHTML='<div class="cms-head"><h3>Site Content</h3><button id="new-content">+ Add content</button></div><div class="cms-list">'+(data||[]).map(x=>'<div class="cms-row"><div><b>'+esc(x.content_key)+'</b><small>'+esc(x.status)+'</small></div><button data-content-id="'+x.id+'">Edit</button></div>').join("")+"</div>";$("#new-content").onclick=()=>contentForm();target.querySelectorAll("[data-content-id]").forEach(b=>b.onclick=()=>contentForm(data.find(x=>x.id===b.dataset.contentId)))}
 if(tab==="logos"){const {data,error}=await db.from("client_logos").select("*").order("sort_order");if(error){target.innerHTML="<p>"+esc(error.message)+"</p>";return}target.innerHTML='<div class="cms-head"><h3>Client Logos</h3><button id="new-logo">+ Add logo</button></div><div class="cms-list">'+(data||[]).map(x=>'<div class="cms-row"><div><b>'+esc(x.name)+'</b><small>'+esc(x.status)+'</small></div><button data-logo-id="'+x.id+'">Edit</button></div>').join("")+"</div>";$("#new-logo").onclick=()=>logoForm();target.querySelectorAll("[data-logo-id]").forEach(b=>b.onclick=()=>logoForm(data.find(x=>x.id===b.dataset.logoId)))}

 if(tab==="pricing"){const {data,error}=await db.from("pricing_plans").select("id,name,market,currency,amount,status,featured").order("market").order("sort_order");if(error){target.innerHTML="<p>"+esc(error.message)+"</p>";return}target.innerHTML='<div class="cms-head"><h3>Pricing</h3><span>Click any plan to edit</span></div><div class="cms-list">'+(data||[]).map(p=>'<div class="cms-row"><div><b>'+esc(p.name)+'</b><small>'+esc(p.market)+' · '+esc(p.currency)+'</small></div><strong>'+Number(p.amount).toLocaleString()+'</strong><span>'+esc(p.status)+'</span><button data-price-id="'+p.id+'">Edit</button></div>').join("")+"</div>";target.querySelectorAll("[data-price-id]").forEach(b=>b.onclick=()=>pricingForm(data.find(x=>x.id===b.dataset.priceId)))}
}
async function projectForm(){const name=prompt("Project name");if(!name)return;const category=prompt("Category / discipline","Brand Identity");if(!category)return;const {error}=await db.from("projects").insert({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),category,client_name:name,short_description:"New ZERO ONE project",status:"draft",featured:false,sort_order:99});if(error)alert(error.message);else adminData("projects")}
async function serviceForm(){const name=prompt("Service name");if(!name)return;const {error}=await db.from("services").insert({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),short_description:"New service",status:"draft",featured:false,sort_order:99});if(error)alert(error.message);else adminData("services")}
){const t=$("#admin-content");t.innerHTML='<div class="cms-editor"><button id="cms-back">← Back</button><h3>Edit Site Content</h3><label>Content key<input id="content-key" value="'+esc(row.content_key||"homepage.hero")+'"></label><label>Content JSON<textarea id="content-json" rows="14">'+esc(JSON.stringify(row.content||{},null,2))+'</textarea></label><label class="check"><input id="content-published" type="checkbox" '+(row.status==="published"?"checked":"")+' > Published</label><button id="cms-save">Save changes</button><p id="cms-msg"></p></div>';$("#cms-back").onclick=()=>adminData("content");$("#cms-save").onclick=async()=>{let obj;try{obj=JSON.parse($("#content-json").value)}catch(e){$("#cms-msg").textContent="Invalid JSON";return}const payload={content_key:$("#content-key").value,content:obj,status:$("#content-published").checked?"published":"draft"};const q=row.id?db.from("site_content").update(payload).eq("id",row.id):db.from("site_content").insert(payload);const {error}=await q;if(error)$("#cms-msg").textContent=error.message;else adminData("content")}}
){const t=$("#admin-content");t.innerHTML='<div class="cms-editor"><button id="cms-back">← Back</button><h3>'+(row.id?"Edit":"New")+' Client Logo</h3><div class="editor-grid"><label>Name<input id="logo-name" value="'+esc(row.name||"")+'"></label><label>Logo URL<input id="logo-url" value="'+esc(row.logo_url||"")+'"></label><label>Website URL<input id="logo-web" value="'+esc(row.website_url||"")+'"></label><label>Sort order<input id="logo-order" value="'+esc(row.sort_order??99)+'"></label></div><label class="check"><input id="logo-published" type="checkbox" '+(row.status==="published"?"checked":"")+' > Published</label><button id="cms-save">Save changes</button><p id="cms-msg"></p></div>';$("#cms-back").onclick=()=>adminData("logos");$("#cms-save").onclick=async()=>{const payload={name:$("#logo-name").value,logo_url:$("#logo-url").value,website_url:$("#logo-web").value,sort_order:Number($("#logo-order").value)||99,status:$("#logo-published").checked?"published":"draft"};const q=row.id?db.from("client_logos").update(payload).eq("id",row.id):db.from("client_logos").insert(payload);const {error}=await q;if(error)$("#cms-msg").textContent=error.message;else adminData("logos")}}
function renderClientLogos(rows){const t=document.querySelector(".marquee .track");if(t&&rows?.length)t.innerHTML=rows.map(x=>esc(x.name)).join(" · ")+" · ZERO ONE"}
function applySiteContent(rows){const map=Object.fromEntries((rows||[]).map(x=>[x.content_key,x.content]));const h=map["homepage.hero"];if(h){if(h.eyebrow)document.querySelector(".hero .eyebrow").textContent=h.eyebrow;if(h.description)document.querySelector(".hero p").textContent=h.description}const a=map["homepage.about"];if(a&&a.description)document.querySelector("#about header p").textContent=a.description}

document.addEventListener("click",e=>{const b=e.target.closest("[data-tab]");if(b){document.querySelectorAll(".admin-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");adminData(b.dataset.tab)}});

function cmsForm(type,row={}){
 const target=$("#admin-content");
 const isP=type==="project", isS=type==="service";
 const fields=isP
 ? [['name','Name'],['category','Category'],['client_name','Client'],['short_description','Short description'],['cover_url','Cover image URL'],['sort_order','Sort order']]
 : [['name','Name'],['eyebrow','Eyebrow'],['short_description','Short description'],['description','Description'],['icon','Icon'],['sort_order','Sort order']];
 target.innerHTML='<div class="cms-editor"><button id="cms-back">← Back</button><h3>'+ (row.id?'Edit ':'New ')+(isP?'Project':'Service')+'</h3><div class="editor-grid">'+fields.map(f=>'<label>'+f[1]+'<input data-field="'+f[0]+'" value="'+esc(row[f[0]]??'')+'"></label>').join('')+'</div><label class="check"><input id="edit-featured" type="checkbox" '+(row.featured?'checked':'')+'> Featured</label><label class="check"><input id="edit-published" type="checkbox" '+(row.status==="published"?'checked':'')+'> Published</label><button id="cms-save">Save changes</button><p id="cms-msg"></p></div>';
 $("#cms-back").onclick=()=>adminData(type+"s");
 $("#cms-save").onclick=async()=>{
   const payload={};target.querySelectorAll("[data-field]").forEach(i=>{let v=i.value;if(i.dataset.field==="sort_order")v=Number(v)||99;payload[i.dataset.field]=v});
   payload.featured=$("#edit-featured").checked;payload.status=$("#edit-published").checked?"published":"draft";
   if(!row.id){payload.slug=(payload.name||"item").toLowerCase().replace(/[^a-z0-9]+/g,"-");if(isP)payload.client_name=payload.client_name||payload.name;payload.status="draft"}
   const q=row.id?db.from(isP?"projects":"services").update(payload).eq("id",row.id):db.from(isP?"projects":"services").insert(payload);
   const {error}=await q;if(error)$("#cms-msg").textContent=error.message;else adminData(type+"s");
 };
}

function contentForm(row={}){const t=$("#admin-content");t.innerHTML='<div class="cms-editor"><button id="cms-back">← Back</button><h3>Edit Site Content</h3><label>Content key<input id="content-key" value="'+esc(row.content_key||"homepage.hero")+'"></label><label>Content JSON<textarea id="content-json" rows="14">'+esc(JSON.stringify(row.content||{},null,2))+'</textarea></label><label class="check"><input id="content-published" type="checkbox" '+(row.status==="published"?"checked":"")+'> Published</label><button id="cms-save">Save changes</button><p id="cms-msg"></p></div>';$("#cms-back").onclick=()=>adminData("content");$("#cms-save").onclick=async()=>{let obj;try{obj=JSON.parse($("#content-json").value)}catch(e){$("#cms-msg").textContent="Invalid JSON";return}const payload={content_key:$("#content-key").value,content:obj,status:$("#content-published").checked?"published":"draft"};const q=row.id?db.from("site_content").update(payload).eq("id",row.id):db.from("site_content").insert(payload);const {error}=await q;if(error)$("#cms-msg").textContent=error.message;else adminData("content")}}
function logoForm(row={}){const t=$("#admin-content");t.innerHTML='<div class="cms-editor"><button id="cms-back">← Back</button><h3>'+(row.id?"Edit":"New")+' Client Logo</h3><div class="editor-grid"><label>Name<input id="logo-name" value="'+esc(row.name||"")+'"></label><label>Logo URL<input id="logo-url" value="'+esc(row.logo_url||"")+'"></label><label>Website URL<input id="logo-web" value="'+esc(row.website_url||"")+'"></label><label>Alt text<input id="logo-alt" value="'+esc(row.alt_text||"")+'"></label><label>Sort order<input id="logo-order" value="'+esc(row.sort_order??99)+'"></label></div><label class="check"><input id="logo-published" type="checkbox" '+(row.status==="published"?"checked":"")+'> Published</label><button id="cms-save">Save changes</button><p id="cms-msg"></p></div>';$("#cms-back").onclick=()=>adminData("logos");$("#cms-save").onclick=async()=>{const payload={name:$("#logo-name").value,logo_url:$("#logo-url").value,website_url:$("#logo-web").value,alt_text:$("#logo-alt").value,sort_order:Number($("#logo-order").value)||99,status:$("#logo-published").checked?"published":"draft"};const q=row.id?db.from("client_logos").update(payload).eq("id",row.id):db.from("client_logos").insert(payload);const {error}=await q;if(error)$("#cms-msg").textContent=error.message;else adminData("logos")}}
function pricingForm(row){
 const target=$("#admin-content"), fields=[["amount","Amount"],["min_amount","Minimum amount"],["max_amount","Maximum amount"],["description","Description"],["billing_label","Billing label"],["cta_label","CTA label"],["sort_order","Sort order"]];
 target.innerHTML='<div class="cms-editor"><button id="cms-back">← Back</button><h3>Edit Pricing</h3><small>'+esc(row.name)+' · '+esc(row.market)+'</small><div class="editor-grid">'+fields.map(f=>'<label>'+f[1]+'<input data-field="'+f[0]+'" value="'+esc(row[f[0]]??"")+'"></label>').join("")+'</div><label class="check"><input id="edit-featured" type="checkbox" '+(row.featured?"checked":"")+'> Featured</label><label class="check"><input id="edit-published" type="checkbox" '+(row.status==="published"?"checked":"")+'> Published</label><button id="cms-save">Save changes</button><p id="cms-msg"></p></div>';
 $("#cms-back").onclick=()=>adminData("pricing");
 $("#cms-save").onclick=async()=>{const payload={};target.querySelectorAll("[data-field]").forEach(i=>{let v=i.value;if(["amount","min_amount","max_amount","sort_order"].includes(i.dataset.field))v=Number(v)||0;payload[i.dataset.field]=v});payload.featured=$("#edit-featured").checked;payload.status=$("#edit-published").checked?"published":"draft";const {error}=await db.from("pricing_plans").update(payload).eq("id",row.id);if(error)$("#cms-msg").textContent=error.message;else adminData("pricing")};
}

function openCaseStudy(slug){if(!slug||!db)return;db.from("projects").select("*").eq("slug",slug).maybeSingle().then(({data})=>{if(!data)return;const g=Array.isArray(data.gallery)?data.gallery:[];const el=document.createElement("div");el.className="case-modal";el.innerHTML='<div class="case-modal-inner"><button class="case-close">×</button><small>'+esc(data.category||"CASE STUDY")+' · '+esc(data.year||"")+'</small><h2>'+esc(data.name)+'</h2><p>'+esc(data.description||data.short_description||"")+'</p><div class="case-gallery">'+g.map(u=>'<img src="'+esc(u)+'" alt="'+esc(data.name)+'">').join("")+'</div></div>';document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add("open"));el.querySelector(".case-close").onclick=()=>el.remove()})}
document.addEventListener("click",e=>{const card=e.target.closest(".project[data-slug]");if(card)openCaseStudy(card.dataset.slug)});
