const SUPABASE_URL="https://wfxaacrxolofifflwsak.supabase.co";
const SUPABASE_KEY="sb_publishable_2mx_ZxJMnKa9hZHOYLHqQQ_aIDNXpwK";
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const PROJECTS_FALLBACK=[["EVORA","Luxury fragrance / Brand world","01","SIGNATURE"],["THE CLOSET","Fashion / Editorial identity","02","THE CLOSET"],["ASAS","Real estate / Brand system","03","ASAS"],["MILESTONE","Engineering / Corporate identity","04","MILESTONE"]];
const SERVICES_FALLBACK=[["01","Brand Identity & Strategy","Positioning, naming, visual systems, art direction and guidelines."],["02","Digital Experiences","Websites, UI/UX and digital systems that feel premium and effortless."],["03","Campaigns & Content","Launch concepts, motion and creative campaigns designed to be noticed."],["04","Growth Creative","Creative direction for paid media, conversion journeys and measurable growth."]];
const PRICES={UAE:["AED",[3000,6000,10000]],KSA:["SAR",[6500,13000,22000]],KWT:["KWD",[250,500,850]],EGY:["EGP",[45000,85000,140000]]};
const OPTIONS=[["posts","Social posts",500],["stories","Stories",250],["reels","Reels",700],["video","Product / Promo Video",1500],["motion","Motion Graphics",1200],["landing","Landing Page",2500],["website","Website",6000],["seo","SEO",2000],["strategy","Strategy & Support",1500],["ads","Ads Management",1800]];
let market="UAE",total=3000,projects=PROJECTS_FALLBACK,services=SERVICES_FALLBACK;

const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function renderProjects(rows){projects=rows?.length?rows.map((p,i)=>[p.name||p.client_name||"PROJECT",p.short_description||p.category||"Creative project",String(i+1).padStart(2,"0"),p.cover_url||p.category||"ZERO ONE"]):PROJECTS_FALLBACK;$("#projects").innerHTML=projects.map(p=>'<article class="project"><div class="project-visual">'+(p[3].startsWith?.("http")?'<img src="'+esc(p[3])+'" alt="'+esc(p[0])+'">':'<div class="project-art">'+esc(p[3])+"</div>")+'</div><div class="project-meta"><div><h3>'+esc(p[0])+'</h3><p>'+esc(p[1])+" · 2026</p></div><span>↗</span></div></article>").join("");}
function renderServices(rows){services=rows?.length?rows.map((s,i)=>[String(i+1).padStart(2,"0"),s.name,s.short_description||s.description||""]):SERVICES_FALLBACK;$("#services-list").innerHTML=services.map(s=>'<article class="service"><span>'+s[0]+'</span><div><h3>'+esc(s[1])+'</h3><p>'+esc(s[2])+'</p></div><b>↗</b></article>').join("");}
function renderPricing(){const [cur,ps]=PRICES[market];$("#plans").innerHTML=ps.map((p,i)=>'<article class="plan '+(i===1?"popular":"")+'"><small>0'+(i+1)+" / "+["STARTER","GROWTH","PREMIUM"][i]+'</small><h3>'+["Starter","Growth","Premium"][i]+'</h3><div class="price">'+cur+" "+p.toLocaleString()+'<small> / MONTH</small></div><ul><li>Creative direction</li><li>Monthly content system</li><li>Strategy & reporting</li><li>Priority support</li></ul><button data-contact>Start a conversation ↗</button></article>').join("");total=ps[0];$("#total").textContent=cur+" "+total.toLocaleString();}
function renderBuilder(){$("#builder-options").innerHTML=OPTIONS.map(o=>'<label class="option"><span>'+o[1]+'</span><input type="checkbox" data-price="'+o[2]+'" data-name="'+esc(o[1])+'"></label>').join("");$("#builder-options").onchange=calc;}
function calc(){const [cur,min]=PRICES[market];let sum=min[0],chosen=[];document.querySelectorAll("#builder-options input:checked").forEach(x=>{sum+=+x.dataset.price;chosen.push(x.dataset.name)});total=sum;$("#total").textContent=cur+" "+sum.toLocaleString();$("#wa").dataset.message="Market: "+market+"\nEstimated monthly investment: "+cur+" "+sum.toLocaleString()+"\nSelected: "+chosen.join(", ");}
async function loadCMS(){if(!db)return;try{const [p,s,pr]=await Promise.all([db.from("projects").select("name,client_name,category,short_description,cover_url").eq("status","published").order("sort_order"),db.from("services").select("name,short_description,description").eq("status","published").order("sort_order"),db.from("pricing_plans").select("*").eq("status","published").eq("market",market).order("sort_order")]);if(!p.error)renderProjects(p.data);if(!s.error)renderServices(s.data);if(!pr.error&&pr.data?.length){const grouped=pr.data.slice(0,3);const cur=grouped[0].currency;const ps=grouped.map(x=>Number(x.amount));PRICES[market]=[cur,ps];renderPricing();calc();}}catch(e){console.warn("CMS fallback",e)}}
async function submitLead(e){e.preventDefault();const form=e.target,d=Object.fromEntries(new FormData(form));const payload={name:d.name,company:d.company,email:d.email,phone:d.phone,whatsapp:d.phone,message:d.message,service_interest:d.service,source:"website",market:market,status:"new"};if(db){const {error}=await db.from("leads").insert(payload);if(error){console.error(error);$("#form-status").textContent="We couldn't send the enquiry. Please use WhatsApp.";return;}}$("#form-status").textContent="Enquiry received. We’ll get back to you shortly.";form.reset();}
async function adminSignIn(){const email=$("#admin-email").value.trim(),pass=$("#admin-pass").value;if(!db||!email||!pass){$("#admin-msg").textContent="Enter valid credentials.";return}const {error}=await db.auth.signInWithPassword({email,password:pass});if(error){$("#admin-msg").textContent=error.message;return}await openDashboard();}
async function openDashboard(){const {data:{user}}=await db.auth.getUser();if(!user){$("#admin-msg").textContent="Sign in required.";return}const role=user.app_metadata?.role;if(role!=="admin"){$("#admin-msg").textContent="This account is not an admin.";await db.auth.signOut();return}$("#admin-login").hidden=true;$("#admin-dash").hidden=false;const {data,error}=await db.from("leads").select("name,email,company,created_at,status").order("created_at",{ascending:false}).limit(50);if(error){$("#admin-msg").textContent=error.message;return}$("#a-leads").firstChild.textContent=data?.length||0;$("#lead-table").innerHTML=(data||[]).map(l=>'<div class="lead-row"><span>'+esc(l.name)+'</span><span>'+esc(l.email)+'</span><span>'+esc(l.company)+'</span><span>'+new Date(l.created_at).toLocaleDateString()+"</span></div>").join("")||"<p>No leads yet.</p>";}
document.querySelectorAll(".market-tabs button").forEach(b=>b.onclick=async()=>{market=b.dataset.market;document.querySelectorAll(".market-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderPricing();calc();await loadCMS();});
$("#wa").onclick=()=>{const msg=$("#wa").dataset.message||"I want to build a custom ZERO ONE package.";location.href="https://wa.me/201556764804?text="+encodeURIComponent(msg)};
$("#lead-form").onsubmit=submitLead;
$("#admin-link").onclick=async()=>{ $("#admin").classList.add("open"); if(db){const {data:{session}}=await db.auth.getSession();if(session)await openDashboard();}};
$("#admin-signin").onclick=adminSignIn;
$("#close-admin").onclick=async()=>{$("#admin").classList.remove("open");if(db)await db.auth.signOut();$("#admin-login").hidden=false;$("#admin-dash").hidden=true;};
document.addEventListener("click",e=>{if(e.target.matches("[data-contact]"))location.hash="contact";});
window.addEventListener("scroll",()=>{$(".scroll-progress span").style.width=(scrollY/(document.body.scrollHeight-innerHeight)*100)+"%"});
renderProjects();renderServices();renderPricing();renderBuilder();loadCMS();

(function(){const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const setup=()=>{document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",()=>{const el=document.querySelector(a.getAttribute("href"));if(el)el.scrollIntoView({behavior:reduced?"auto":"smooth"})}));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".project,.service,.plan,.process-grid article,.about-grid,.builder").forEach(e=>{e.classList.add("reveal-ready");io.observe(e)});const hero=document.querySelector(".hero-art"),island=document.querySelector(".island-stage");if(hero&&!reduced&&window.matchMedia("(pointer:fine)").matches)hero.addEventListener("pointermove",e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;island.style.transform="translate("+x*18+"px,"+y*14+"px)"});hero?.addEventListener("pointerleave",()=>island.style.transform="");document.querySelector(".menu")?.addEventListener("click",()=>document.querySelector(".nav-wrap").classList.toggle("mobile-open"));};setup();})();